### ISSUE TITLE
Problem with media_private

### ISSUE THREAD

**Issue by odlex** [BRACKETS-by-TRIAD/media#3]
Hy,
I have a 404 error when i want access files on the media_private disk

I solved that by adding 
` 
$this->app['config']->set('medialibrary.custom_url_generator_class', \Brackets\Media\UrlGenerator\LocalUrlGenerator::class);
`
in the register() function of MediaServiceProvider

**Comment by palypster** [comment]
I think this depends on how you generate the URL for private media. I have checked our documentation and I agree this is not documented well. Can you paste a snippet here?
