### ISSUE TITLE
Can 'HasMediaCollectionsTrait' works with file sending in via API?

### ISSUE THREAD

**Issue by Trexology** [BRACKETS-by-TRIAD/media#6]
I have made my Post Model with HasMediaCollectionsTrait on it.

Tried to send in a create Post function via API using Postman app (content-type: form-data) with the attachment on it. But got an error message

 "message": "Illegal string offset 'action'",
    "exception": "ErrorException",
    "file": "/var/www/vendor/brackets/media/src/HasMedia/HasMediaCollectionsTrait.php",
    "line": 114,

**Comment by palypster** [comment]
Uploading media and attaching to the model are two separate things. HasMediaCollections handles the attaching already uploaded media to the model using specific array structure send withing the save model request:
https://docs.getcraftable.com/v2/#/media?id=attaching-media-to-model

you can of course build this specific structure by your own or you can use our prepared element:
https://docs.getcraftable.com/v2/#/media?id=uploader

The uploader element also handles the upload itself (checkout the FileUploadController inside this package), but if you are not using it, you have to handle the uploads on your own.
